### ISSUE TITLE
[Breaking Change] MapieRegressor removed in v1.x with no migration guidance

### ISSUE THREAD

**Issue by Tamish03** [scikit-learn-contrib/MAPIE#915]
<html>
<body>
<html><head></head><body><h1>[Breaking Change] MapieRegressor removed in v1.x with no migration guidance</h1><h2>Summary</h2><p><code inline="">MapieRegressor</code> was removed in MAPIE 1.x without a compatibility shim, deprecation warning, or official migration pathway for users upgrading from MAPIE 0.x tutorials and notebooks.</p><p>Any user following pre-1.0 MAPIE examples immediately encounters:</p><pre><code class="language-python">from mapie.regression import MapieRegressor
</code></pre><p>which now raises:</p><pre><code class="language-python">ImportError: cannot import name 'MapieRegressor'
</code></pre><p>This creates significant onboarding friction for practitioners migrating from older notebooks, Kaggle examples, blog posts, and StackOverflow solutions.</p><p>While debugging this in a Kaggle + Python 3.12 environment, I confirmed that MAPIE 1.x introduced a complete architectural redesign replacing <code inline="">MapieRegressor</code> with specialized conformal regression classes.</p><h2>Environment</h2><pre><code class="language-txt">Python: 3.12.x
MAPIE: 1.4.0
scikit-learn: 1.6.1
Environment: Kaggle Notebook / Linux
</code></pre><h2>Steps to Reproduce</h2><pre><code class="language-python">pip install mapie

from mapie.regression import MapieRegressor
</code></pre><h2>Expected Behavior</h2><p>Either:</p><ol><li><p><code inline="">MapieRegressor</code> should exist as a compatibility shim emitting a <code inline="">DeprecationWarning</code></p></li></ol><p>OR</p><ol start="2"><li><p>The ImportError should guide users toward the new replacement classes such as:</p><ul><li><p><code inline="">CrossConformalRegressor</code></p></li><li><p><code inline="">SplitConformalRegressor</code></p></li><li><p><code inline="">ConformalizedQuantileRegressor</code></p></li></ul></li></ol><p>OR</p><ol start="3"><li><p>Official migration documentation should clearly explain:</p><ul><li><p>old → new class mappings</p></li><li><p>predict() signature changes</p></li><li><p>alpha → confidence_level migration</p></li></ul></li></ol><h2>Actual Behavior</h2><pre><code class="language-python">ImportError: cannot import name 'MapieRegressor' from 'mapie.regression'
</code></pre><p>No migration guidance or replacement suggestions are provided.</p><h2>Suggested Fix</h2><p>Possible improvements:</p><ul><li><p>Add a lightweight compatibility shim for <code inline="">MapieRegressor</code></p></li><li><p>Raise a custom migration-aware error message</p></li><li><p>Add a dedicated 0.x → 1.x migration guide</p></li><li><p>Add notebook migration examples for Kaggle/Colab users</p></li></ul><p>Example compatibility guidance:</p>
MAPIE 0.x | MAPIE 1.x
-- | --
MapieRegressor(method='plus') | CrossConformalRegressor
MapieRegressor(method='base') | SplitConformalRegressor
method='quantile' | ConformalizedQuantileRegressor

<p>I'm also happy to contribute documentation or a migration guide PR if maintainers think it would be useful.</p></body></html>
</body>
</html>

**Comment by GBrelurut** [comment]
Hello @Tamish03,
Thank you very much for taking the time to detail the issue and to suggest a fix.

However we already have an exhaustive migration guide in the documentation : https://contrib.scikit-learn.org/MAPIE/stable/getting-started/v1-release-notes/#key-changes (see here for the raw file : https://github.com/scikit-learn-contrib/MAPIE/blob/master/doc/getting-started/v1-release-notes.md). 
It is already accessible via the index page of the documentation. Plus we wanted to delete this file by the end of next month ( see issue #750 ).

Do you think this satisfactorily solves the issue ? If not, can you tell us how to make the guide more accessible and if we should keep it more than we previously anticipated ?

**Comment by Tamish03** [comment]
Hello @GBrelurut,

Thank you very much for the clarification and for pointing me to the existing migration guide and release notes.

After reviewing the documentation more carefully, I do agree that the migration information itself is already quite comprehensive. My confusion mainly came from the onboarding/discoverability side rather than missing technical details.

While working in a Kaggle + Python 3.12 environment, I initially encountered:

```python
ImportError: cannot import name 'MapieRegressor'
```

and my first instinct was to search directly around the import/API transition rather than the release notes section. I suspect newer users following older notebooks/tutorials may experience something similar.

From a beginner/user onboarding perspective, I think a few small discoverability improvements could still help significantly, for example:

* adding a short migration note directly near common regression imports/examples
* adding a visible “Coming from MAPIE 0.x?” pointer in quick-start/install pages
* adding a short note in ImportError troubleshooting guidance
* extending visibility of the v1 migration notes a bit longer before removal

I especially think the current migration guide is valuable for:

* Kaggle users
* notebook-based learners
* users upgrading older tutorials/blog examples
* Python 3.12 environments where users often attempt version downgrades first

So personally, I think keeping the migration guide accessible for a little longer could still reduce onboarding friction for newer users.

Thank you again for the clarification and for maintaining the project. I’d still be happy to help contribute smaller documentation/onboarding improvements if useful.

**Comment by GBrelurut** [comment]
@Tamish03 Thank you for your feedback. We will see how we can handle the problem as quickly as possible.
